# Generated by Django 5.1.7 on 2025-03-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
