# Generated by Django 5.1.7 on 2025-03-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_paid',
            new_name='paid',
        ),
    ]
