# Generated by Django 5.1.7 on 2025-03-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_rename_is_paid_booking_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
