# Generated by Django 5.1.7 on 2025-03-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_doctors_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='dep_name',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
