# Generated by Django 5.1.7 on 2025-03-25 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_doctors_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=50, unique=True)),
                ('payment_status', models.BooleanField(default=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.booking')),
            ],
        ),
    ]
